import type { FirestoreAdapter } from '../db';
import { WorkerError } from '../db';
// crypto.randomUUID is available on the global scope in Cloudflare
// Workers (Web Crypto API) and modern Node. No import needed.

const FIVE_MINUTES_MS = 5 * 60 * 1000;

function contentTypeToExt(ct: string): string {
  switch (ct) {
    case 'image/png': return '.png';
    case 'image/jpeg': return '.jpg';
    case 'image/webp': return '.webp';
    case 'image/gif': return '.gif';
    default: return '';
  }
}

export type SignedUploadInput = { contentType: string; fileExt?: string };
export type SignedUploadOutput = { url: string; path: string; expires: number };

/**
 * Pure helper: validates content type + returns a signed-upload spec.
 * The actual signed URL is generated by the R2 binding in production
 * (see src/r2.ts); this function stays pure for tests.
 */
export function buildSignedUploadSpec(
  uid: string,
  input: SignedUploadInput,
  now: () => number = () => Date.now(),
): { path: string; expires: number; contentType: string } {
  if (!input.contentType || !input.contentType.startsWith('image/')) {
    throw new WorkerError(
      'invalid-argument',
      'contentType must be an image/* MIME type.',
    );
  }
  const ext = input.fileExt ?? contentTypeToExt(input.contentType);
  const filename = `${crypto.randomUUID()}${ext}`;
  const path = `paymentRequests/${uid}/${filename}`;
  const expires = now() + FIVE_MINUTES_MS;
  return { path, expires, contentType: input.contentType };
}

/**
 * Convenience that combines buildSignedUploadSpec with the R2 signer.
 * R2 is injected so tests can stub it.
 */
export interface R2Signer {
  signPutUrl(path: string, contentType: string, expires: number): Promise<string>;
}

export async function generateSignedUploadUrl(
  uid: string,
  input: SignedUploadInput,
  r2: R2Signer,
  now: () => number = () => Date.now(),
): Promise<SignedUploadOutput> {
  const spec = buildSignedUploadSpec(uid, input, now);
  const url = await r2.signPutUrl(spec.path, spec.contentType, spec.expires);
  return { url, path: spec.path, expires: spec.expires };
}