#!/usr/bin/env bash
# Interactive: set up apps/web/.env.production from your Supabase +
# Cloudflare values. The values you enter here are written to
# apps/web/.env.production, which IS GITIGNORED.
#
# Run this from a terminal, NOT from the agent (the values are typed in
# interactively and never go into chat history).
#
# You need:
#   - Supabase URL + anon key from Supabase dashboard → Project Settings → API
#   - 2 Sentry values from sentry.io → Project Settings → Client Keys
#     (DSN); leave DSN blank if you don't have Sentry set up yet

set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE="apps/web/.env.production"

if [ -f "$ENV_FILE" ]; then
  echo "WARN: $ENV_FILE already exists. Overwrite? (y/N)"
  read -r ans
  case "$ans" in
    [yY]*) ;;
    *)     echo "aborting"; exit 1 ;;
  esac
fi

echo ""
echo "Fill in the values:"
echo ""

read -p "VITE_SUPABASE_URL:      " VITE_SUPABASE_URL
read -p "VITE_SUPABASE_ANON_KEY: " VITE_SUPABASE_ANON_KEY
read -p "VITE_SENTRY_DSN (or blank): " VITE_SENTRY_DSN

cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE.

VITE_SUPABASE_URL=$VITE_SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY

VITE_SENTRY_DSN=$VITE_SENTRY_DSN
VITE_SENTRY_ENVIRONMENT=production

VITE_WORKERS_BASE=https://hsc-tracker-ef2b5-workers.byzubooo.workers.dev

VITE_ENABLE_TEST_ROUTES=false
VITE_E2E_UID=e2e-mock-uid
EOF

echo ""
echo "✓ Wrote $ENV_FILE"
echo "  Next: set worker secret (wrangler secret put SUPABASE_SERVICE_KEY),"
echo "  apply supabase/migrations/0001_init.sql, then run scripts/deploy.mjs"
