#!/usr/bin/env bash
# Interactive: set up apps/web/.env.production from your real Firebase +
# Cloudflare values. The values you enter here are written to
# apps/web/.env.production, which IS GITIGNORED.
#
# Run this from a terminal, NOT from the agent (the values are typed in
# interactively and never go into chat history).
#
# You need:
#   - 6 Firebase web SDK values from Firebase Console → Project Settings
#     → Your apps → SDK setup → copy firebaseConfig block
#   - 2 Sentry values from sentry.io → Project Settings → Client Keys
#     (DSN); leave DSN blank if you don't have Sentry set up yet

set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE="apps/web/.env.production"

if [ -f "$ENV_FILE" ]; then
  echo "WARN: $ENV_FILE already exists. Overwrite? (y/N)"
  read -r ans
  case "$ans" in
    [yY]*) ;;
    *)     echo "aborting"; exit 1 ;;
  esac
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE.

VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID

VITE_SENTRY_DSN=
VITE_SENTRY_ENVIRONMENT=production

VITE_ENABLE_TEST_ROUTES=false
VITE_E2E_UID=e2e-mock-uid
EOF

echo ""
echo "Wrote template to $ENV_FILE. Now fill in the values:"
echo ""

read -p "VITE_FIREBASE_API_KEY:            " VITE_FIREBASE_API_KEY
read -p "VITE_FIREBASE_AUTH_DOMAIN:        " VITE_FIREBASE_AUTH_DOMAIN
read -p "VITE_FIREBASE_PROJECT_ID:         " VITE_FIREBASE_PROJECT_ID
read -p "VITE_FIREBASE_STORAGE_BUCKET:     " VITE_FIREBASE_STORAGE_BUCKET
read -p "VITE_FIREBASE_MESSAGING_SENDER_ID:" VITE_FIREBASE_MESSAGING_SENDER_ID
read -p "VITE_FIREBASE_APP_ID:             " VITE_FIREBASE_APP_ID
read -p "VITE_SENTRY_DSN (or blank):       " VITE_SENTRY_DSN

cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE.

VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID

VITE_SENTRY_DSN=$VITE_SENTRY_DSN
VITE_SENTRY_ENVIRONMENT=production

VITE_ENABLE_TEST_ROUTES=false
VITE_E2E_UID=e2e-mock-uid
EOF

echo ""
echo "✓ Wrote $ENV_FILE"
echo "  Next: run scripts/deploy.mjs (or the wrangler step-by-step commands in HANDOFF.md)"
